name: PR Checks

on:
    pull_request:
        branches:
            - master

jobs:
    tests:
        name: Run Tests
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:8
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: testing
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  coverage: xdebug

            - name: Install dependencies
              run: composer install --no-progress --prefer-dist

            - name: Set up Laravel environment
              run: |
                  cp .env.example .env
                  php artisan key:generate
                  php artisan migrate --force

            - name: Run tests with coverage check
              run: composer test
